---
title: "Análisis Factorial confirmatorio"
output: html_notebook
---

## Introducción

Diferencia entre encuestas y test psicológico, encuestas no tienen variables latentes y las preguntas no se suman. Una encuesta no necesita tener estructura interna.

Se usan técnicas para ver la fiabilidad del test

## TCT

Teoría Clásica de los Test habla de estudiar al test en su conjunto. Nos da información detallada de los ítems.

### Fiabilidad

TEST - RE-TEST (estabilidad temporal)

Formas - Paralelas

Consistencia internta ($\alpha$ de Cronbach). Se analiza qué tanto son los instrumentos consistentes entre ellos. Los pone en relación unos con otros, de tal manera que nos da un único índice. Tiene diversos problemas, considerando que entre más ítems más consistencia, sin que necesariamente estén relacionados. Da pistas cuando el instrumento tiene varianzas no consistentes.


Tengo que ser capaz de construir dos intrumentos de medición distintos para medir el mismo constructo pero con ítems distintos.

### Validez

El instrumento mida lo que dice que mide. 

* Validez factorial
  * AF exploratorio[Se dan datos para que las estructuras se parezcan a lo deseado]
  * AF confirmatorio[Se propone una estructura y ver cuánto se ajustan los datos al modelo propuestos]
* Contenido (teórico)
* Convergente[Se comparan instrumentos que midan la dirección de lo que quieran medir] y discriminante[Ver si los instrumentos son capaces de clasificar o identificar grupos]

## AF Exploratorio

Tomar en cuenta

- Teoría
- Auto valores
- Varianza explicada

### Decisiones previas

1. Realizar una representación gráfica del modelo.
2. Estudiar si el modelo está identificado.
3. Estimar los parámetros del modelo.
4. Obtener indicadores del ajuste del modelo.

###

Diagrama de flujo 

Círculos significan constructos (factores) y errores de medida.
Ítems son cuadrados.
Flechas de dos puntas para indicar covariación
Flechas de una punta para indicar que algo influye en ese factor.

Las flechas siempre van siempre hacia los ítems de las dimensiones.

Cuando no hay covarianza entre dimensiones, es que son independientes.

### Conceptos básicos

$$X_j = \sum_{m = 1}^M \lambda_{jm}F_m + E_j$$

Pesos estandarizados

Siempre se fijarán parámetros de factores



Cuidar que el modelo no esté sobreidentificado para no simplificar demasiado la realidad.

Función de Máxima-Verosimilud se debe cumplir el supuesto de normalidad ($\mu = 0, \, \sigma = 1$)

Objetivo, método, resultados, índices de validez