---
title: "Gráficos 3D"
author: "Miguel Hernández"
date: "11/8/2019"
output: html_document
---  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```  

## Building the plot

Using `plotly` to plot a 3D scatter plot of 3 factors from a Factor Analysis.  First: data  

```{r data}
af_sin_rotar = data.frame(
  items = c(
    "IE1", "IE2", "IE3", "IE4", "IE5", "IE6", "IE7", "IE8",
    "IE9", "IE10", "IE11", "IE12", "IE13", "IE14", "IE15", "IE16",
    "IE17", "IE18", "IE19", "IE20", "IE21", "IE22", "IE23", "IE24"
  ),
  CP1 = c(
    0.604, 0.665, 0.632, 0.664, 0.182, 0.43, 0.563, 0.68,
    0.445, 0.582, 0.542, 0.432, 0.5, 0.584, 0.615, 0.568,
    0.326, 0.42, 0.357, 0.449, 0.362, 0.579, 0.309, 0.355
  ),
  CP2 = c(
    -0.427, -0.48, -0.344, -0.31, -0.591, -0.516, -0.575, -0.518,
    0.349, 0.156, 0.28, 0.094, 0.128, 0.109, 0.069, 0.267,
    0.631, 0.637, 0.448, 0.63, 0.353, 0.093, 0.084, 0.339
  ),
  CP3 = c(
    0.099, 0.118, 0.082, 0.169, 0.19, 0.185, 0.223, 0.135,
    -0.343, -0.556, -0.515, -0.29, -0.065, -0.527, -0.234, -0.412,
    0.322, 0.468, 0.43, 0.458, 0.248, 0.26, 0.004, 0.177
  ),
  Latente = c(
    rep("Atención", times = 8),
    rep("Claridad", times = 8),
    rep("Reparación", times = 8)
  )
)

af_varimax = data.frame(
  items = c(
    "IE1", "IE2", "IE3", "IE4", "IE5", "IE6", "IE7", "IE8",
    "IE9", "IE10", "IE11", "IE12", "IE13", "IE14", "IE15", "IE16",
    "IE17", "IE18", "IE19", "IE20", "IE21", "IE22", "IE23", "IE24"
  ),
  CP1 = c(0.721, 0.803, 0.675, 0.697, 0.589, 0.696, 0.834, 0.844,
          -0.058, 0.104, 0.003, 0.129, 0.215, 0.147, 0.281, 0.058,
          -0.137, -0.038, 0.043, -0.017, 0.059, 0.386, 0.143, 0.044),
  CP2 = c(0.19, 0.2, 0.242, 0.206, -0.183, -0.005, 0.033, 0.187, 0.622,
          0.813, 0.79, 0.507, 0.393, 0.78, 0.573, 0.727, 0.131, 0.083,
          0.023, 0.107, 0.135, 0.193, 0.211, 0.18),
  CP3 = c(0.044, 0.048, 0.102, 0.191, -0.195, -0.039, 0.004, 0.04,
          0.219, 0.022, 0.112, 0.077, 0.266, 0.01, 0.175, 0.177, 0.756,
          0.891, 0.715, 0.893, 0.544, 0.475, 0.194, 0.488),
  Latente = c(
    rep("Atención", times = 8),
    rep("Claridad", times = 8),
    rep("Reparación", times = 8)
  )
)

```

## Building layout

Coding 

```{r plotly}
library(plotly)

p_1 = plot_ly(
  af_sin_rotar,
  x = ~ CP1,
  y = ~ CP2,
  z = ~ CP3,
  color = ~ Latente
)
p_1 = add_markers(p_1)
p_1 = layout(
  p_1,
  title = 'Gráfico de factor en espacio de factores sin rotar',
  scene = list(
    xaxis = list(title = "Componente Principal 1"),
    yaxis = list(title = "Componente Principal 2"),
    zaxis = list(title = "Componente Principal 3")
  ),
  xaxis = list(range = c(-1, 1)),
  yaxis = list(range = c(-1, 1))
)

p_2 = plot_ly(
  af_varimax,
  x = ~ CP1,
  y = ~ CP2,
  z = ~ CP3,
  color = ~ Latente
)
p_2 = add_markers(p_2)
p_2 = layout(
  p_2,
  title = 'Gráfico de factor en espacio de factores rotados con Varimax',
  scene = list(
    xaxis = list(title = "Componente Principal 1"),
    yaxis = list(title = "Componente Principal 2"),
    zaxis = list(title = "Componente Principal 3")
  ),
  xaxis = list(range = c(-1, 1)),
  yaxis = list(range = c(-1, 1))
)

```

## Display plot

Unrotated plot

```{r}
p_1
```

Rotated plot

```{r}
p_2
```

