---
title: "skim"
author: "Miguel Hernández"
date: "12/7/2019"
output: 
  pdf_document:
    latex_engine: xelatex
    number_section: true
lang: es
mainfont: Open Sans
bibliography: ref/refm3.bib
abstract: | 
  Se utilizaron análisis de componentes principales, análisis factorial, escalamiento multidimensional y coordenadas principales
  
  **Palabras clave**: Análisis, Multivariante, Factorial, Discriminante, Escalamiento Multidimensional, Coordenadas principales
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Hmisc)
# library(xtable)
library(magrittr)
library(psych)
library(FactoMineR)
library(factoextra)
library(ggrepel)
library(cluster)
library(smacof)
library(ggthemes)
library(skimr)
```

##  Tablas

Imprimir tablas en R es complicado.

Primero carguemos datos:

```{r}
alim = foreign::read.spss("data/M3/PaisesProteinasExamen.sav", to.data.frame = T)
alim$Pais = trimws(alim$Pais)
```


Primero usemos `summary()`:

```{r}
summary(alim)
```

Luego usemos `skimr`

## La buena

```{r, echo=FALSE}
library(skimr)
alim2 = alim
colnames(alim2) = c("País", "Carne roja", "Carne blanca", "Huevos", "Leche", "Pescado", "Cereales", "Féculas", "Frutos secos", "Frutos y vegetales", "Comunista", "Localización")

mi_skim =
  skim_with(
    character = sfl(
      empty = NULL,
      whitespace = NULL
    ),
    numeric = sfl(hist = NULL)
  )

eskim = mi_skim(alim2)

eskim$n_missing = NULL
eskim$complete_rate = NULL

res_eskim = summary(eskim)
rownames(res_eskim) = c(
  "Nombre",
  "Número de filas",
  "Número de columnas",
  "_________________________ ",
  "Frecuencia de cada tipo: ",
  "character",
  "factor", 
  "numeric",
  "_________________________  ",
  "Variables de agrupación"
)
res_eskim[10, 1] = "Ninguna"

knitr::kable(res_eskim, caption = "Resumen general", col.names = "Valores")
#knitr::kable(summary(eskim), caption = "Resumen general", col.names = "Valores")
knitr::kable(partition(eskim)[[1]],
             caption = "Resumen de variable tipo **character**",
             col.names = c("", "Mín", "Máx", "Únicos"))

knitr::kable(partition(eskim)[[2]],
             caption = "Resumen de variable tipo **factor**",
             col.names = c("", "Ordenado", "Único", "Conteo"))

knitr::kable(partition(eskim)[[3]],
             caption = "Resumen de variable tipo **numeric**",
             col.names = c("", "Media", "D.E.", "Q1", "Q2", "Q3", "Q4", "Q5"),
             digits = 3)
```

