* Encoding: UTF-8.
DATASET ACTIVATE DataSet1.
FACTOR
  /VARIABLES Matematicas Naturales Francés Latín
  /MISSING LISTWISE 
  /ANALYSIS Matematicas Naturales Francés Latín
  /PRINT CORRELATION SIG DET KMO INV REPR AIC ROTATION
  /CRITERIA FACTORS(2) ITERATE(25)
  /PLOT EIGEN ROTATION
  /EXTRACTION PC
  /CRITERIA ITERATE(25)
  /ROTATION VARIMAX
  /SAVE AR(ALL)
  /METHOD=CORRELATION.
